/** This file is generated by svg.js. DO NOT MODIFY * */

import IconAdd from './add.svg'
import IconBorderDisabled from './border-disabled.svg'
import IconBorderError from './border-error.svg'
import IconBorder from './border.svg'
import IconClose from './close.svg'
import IconGithub from './github.svg'
import IconInvisible from './invisible.svg'
import IconPriceColorInverse from './price-color-inverse.svg'
import IconPriceColor from './price-color.svg'
import IconTrash from './trash.svg'
import IconTwitter from './twitter.svg'
import IconVisible from './visible.svg'

export {
  IconAdd,
  IconBorderDisabled,
  IconBorderError,
  IconBorder,
  IconClose,
  IconGithub,
  IconInvisible,
  IconPriceColorInverse,
  IconPriceColor,
  IconTrash,
  IconTwitter,
  IconVisible,
}
