/* This file is generated by svg.js. DO NOT MODIFY */

import IconAdd from './add.svg'
import IconBox from './box.svg'
import IconClose from './close.svg'
import IconCoin from './coin.svg'
import IconFontSizeLarge from './font-size-large.svg'
import IconFontSize from './font-size.svg'
import IconGithub from './github.svg'
import IconInvisible from './invisible.svg'
import IconJike from './jike.svg'
import IconPercentage from './percentage.svg'
import IconPriceColorInverse from './price-color-inverse.svg'
import IconPriceColor from './price-color.svg'
import IconTrash from './trash.svg'
import IconTwitter from './twitter.svg'
import IconVisible from './visible.svg'

export {
  IconAdd,
  IconBox,
  IconClose,
  IconCoin,
  IconFontSizeLarge,
  IconFontSize,
  IconGithub,
  IconInvisible,
  IconJike,
  IconPercentage,
  IconPriceColorInverse,
  IconPriceColor,
  IconTrash,
  IconTwitter,
  IconVisible,
}
